name: publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and build
        run: yarn install --prefer-offline && yarn compile

      - name: Compile
        run: yarn compile

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
